micronaut:
  application:
    name: micronautguide
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/micronaut`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
